AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ZippedLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zipped-lambda
      Handler: main.handler
      Runtime: nodejs18.x
      CodeUri: .sam/unzipped
